name: ItemsAdder-ProjectE
version: '$version'

main: ak.ak32767.projecte.ProjectE
api-version: '1.21.5'
load: POSTWORLD
depend:
  - ItemsAdder

commands:
  getemc:
    usage: /<command> [material]
  calcemc:
    usage: /<c0mmand>
  getplayeremc:
    usage: /<command>
  setplayeremc:
    usage: /<command> [value]
  dgui: