name: ItemsAdder-ProjectE
version: '$version'

main: ak.ak32767.projecte.ProjectE
api-version: '1.21.5'
load: POSTWORLD
depend:
  - ItemsAdder

commands:
  projecte: {}
  getemc: {}
  calcemc: {}
  getplayeremc: {}
  setplayeremc: {}
  dgui: {}