name: ItemsAdder-ProjectE
version: '$version'

main: ak.ak32767.projecte.ProjectE
api-version: '1.21.5'
load: POSTWORLD
depend:
  - ItemsAdder

commands:
  projecte: {}
  getemc: {}
  calcemc: {}
  getplayeremc: {}
  setplayeremc: {}
  dgui: {}

  permissions:
    projecte.admin:
      default: op
    projecte.reload:
      default: op

    projecte.transtable.learn:
      default: true
    projecte.transtable.unlearn:
      default: true
    projecte.transtable.transmute:
      default: true
    projecte.transtable.extract:
      default: true

    projecte.philostone.transitem:
      default: true
    projecte.philostone.transblock:
      default: true

